
acquisition:
  intrinsics:
    fx: 577.848511
    fy: 577.848511
    cx: 310.629883
    cy: 230.258133
    width: 640
    height: 480
  distortion: 
    k1: -0.096883
    k2: 0.246684
    k3: -0.257924
    k4: 0.000000
    k5: 0.000000
    k6: 0.000000
    p1: 0.001586
    p2: -0.001464